// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countAdmins = `-- name: CountAdmins :one
SELECT COUNT(*) FROM users WHERE role = 'admin'
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMatchAdmin = `-- name: CreateMatchAdmin :execlastid
INSERT INTO matches
  (source_id, match_number, stage, round, group_letter, match_label,
   home_team_id, away_team_id, kickoff_utc, status, manual_override)
VALUES
  ((SELECT COALESCE(MAX(source_id),0)+1 FROM matches AS m2),
   ?, ?, ?, '', '', ?, ?, ?, 'scheduled', 1)
`

type CreateMatchAdminParams struct {
	MatchNumber int32         `json:"match_number"`
	Stage       MatchesStage  `json:"stage"`
	Round       string        `json:"round"`
	HomeTeamID  sql.NullInt64 `json:"home_team_id"`
	AwayTeamID  sql.NullInt64 `json:"away_team_id"`
	KickoffUtc  time.Time     `json:"kickoff_utc"`
}

func (q *Queries) CreateMatchAdmin(ctx context.Context, arg CreateMatchAdminParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createMatchAdmin,
		arg.MatchNumber,
		arg.Stage,
		arg.Round,
		arg.HomeTeamID,
		arg.AwayTeamID,
		arg.KickoffUtc,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteMatchAdmin = `-- name: DeleteMatchAdmin :execrows
DELETE FROM matches WHERE id = ?
`

func (q *Queries) DeleteMatchAdmin(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMatchAdmin, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getUserRole = `-- name: GetUserRole :one
SELECT role FROM users WHERE id = ?
`

func (q *Queries) GetUserRole(ctx context.Context, id int64) (UsersRole, error) {
	row := q.db.QueryRowContext(ctx, getUserRole, id)
	var role UsersRole
	err := row.Scan(&role)
	return role, err
}

const listMatchesForAdmin = `-- name: ListMatchesForAdmin :many
SELECT m.id, m.match_number, m.stage, m.round,
       m.home_team_id, ht.name AS home_team, ht.code AS home_code,
       m.away_team_id, at.name AS away_team, at.code AS away_code,
       m.kickoff_utc, m.status, m.home_score, m.away_score,
       m.went_to_penalties, m.penalty_winner_team_id, m.manual_override
FROM matches m
LEFT JOIN teams ht ON ht.id = m.home_team_id
LEFT JOIN teams at ON at.id = m.away_team_id
ORDER BY m.kickoff_utc ASC, m.id ASC
`

type ListMatchesForAdminRow struct {
	ID                  int64          `json:"id"`
	MatchNumber         int32          `json:"match_number"`
	Stage               MatchesStage   `json:"stage"`
	Round               string         `json:"round"`
	HomeTeamID          sql.NullInt64  `json:"home_team_id"`
	HomeTeam            sql.NullString `json:"home_team"`
	HomeCode            sql.NullString `json:"home_code"`
	AwayTeamID          sql.NullInt64  `json:"away_team_id"`
	AwayTeam            sql.NullString `json:"away_team"`
	AwayCode            sql.NullString `json:"away_code"`
	KickoffUtc          time.Time      `json:"kickoff_utc"`
	Status              MatchesStatus  `json:"status"`
	HomeScore           sql.NullInt32  `json:"home_score"`
	AwayScore           sql.NullInt32  `json:"away_score"`
	WentToPenalties     bool           `json:"went_to_penalties"`
	PenaltyWinnerTeamID sql.NullInt64  `json:"penalty_winner_team_id"`
	ManualOverride      bool           `json:"manual_override"`
}

func (q *Queries) ListMatchesForAdmin(ctx context.Context) ([]ListMatchesForAdminRow, error) {
	rows, err := q.db.QueryContext(ctx, listMatchesForAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchesForAdminRow
	for rows.Next() {
		var i ListMatchesForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchNumber,
			&i.Stage,
			&i.Round,
			&i.HomeTeamID,
			&i.HomeTeam,
			&i.HomeCode,
			&i.AwayTeamID,
			&i.AwayTeam,
			&i.AwayCode,
			&i.KickoffUtc,
			&i.Status,
			&i.HomeScore,
			&i.AwayScore,
			&i.WentToPenalties,
			&i.PenaltyWinnerTeamID,
			&i.ManualOverride,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersAdmin = `-- name: ListUsersAdmin :many
SELECT
    u.id, u.email, u.name, u.avatar_url, u.role,
    CAST((SELECT COUNT(*) FROM predictions p WHERE p.user_id = u.id) AS SIGNED) AS prediction_count,
    CAST(
        COALESCE((SELECT SUM(COALESCE(p.points, 0) + COALESCE(p.penalty_bonus, 0))
                  FROM predictions p WHERE p.user_id = u.id), 0)
        + COALESCE((SELECT SUM(COALESCE(b.points, 0))
                    FROM bonus_predictions b WHERE b.user_id = u.id), 0)
    AS SIGNED) AS total_points
FROM users u
ORDER BY u.name ASC, u.email ASC
`

type ListUsersAdminRow struct {
	ID              int64     `json:"id"`
	Email           string    `json:"email"`
	Name            string    `json:"name"`
	AvatarUrl       string    `json:"avatar_url"`
	Role            UsersRole `json:"role"`
	PredictionCount int64     `json:"prediction_count"`
	TotalPoints     int64     `json:"total_points"`
}

func (q *Queries) ListUsersAdmin(ctx context.Context) ([]ListUsersAdminRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsersAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersAdminRow
	for rows.Next() {
		var i ListUsersAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.AvatarUrl,
			&i.Role,
			&i.PredictionCount,
			&i.TotalPoints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const matchExists = `-- name: MatchExists :one
SELECT COUNT(*) FROM matches WHERE id = ?
`

func (q *Queries) MatchExists(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, matchExists, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const setMatchManualOverride = `-- name: SetMatchManualOverride :exec
UPDATE matches SET manual_override = 1 WHERE id = ?
`

func (q *Queries) SetMatchManualOverride(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, setMatchManualOverride, id)
	return err
}

const updateMatchDetailAdmin = `-- name: UpdateMatchDetailAdmin :exec
UPDATE matches
SET home_team_id = ?, away_team_id = ?, kickoff_utc = ?, stage = ?, round = ?, manual_override = 1
WHERE id = ?
`

type UpdateMatchDetailAdminParams struct {
	HomeTeamID sql.NullInt64 `json:"home_team_id"`
	AwayTeamID sql.NullInt64 `json:"away_team_id"`
	KickoffUtc time.Time     `json:"kickoff_utc"`
	Stage      MatchesStage  `json:"stage"`
	Round      string        `json:"round"`
	ID         int64         `json:"id"`
}

func (q *Queries) UpdateMatchDetailAdmin(ctx context.Context, arg UpdateMatchDetailAdminParams) error {
	_, err := q.db.ExecContext(ctx, updateMatchDetailAdmin,
		arg.HomeTeamID,
		arg.AwayTeamID,
		arg.KickoffUtc,
		arg.Stage,
		arg.Round,
		arg.ID,
	)
	return err
}
