// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: celebrations.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const listUnseenFinalMatchesForUser = `-- name: ListUnseenFinalMatchesForUser :many
SELECT m.id                     AS match_id,
       ht.id                    AS home_id,
       ht.code                  AS home_code,
       m.home_score             AS home_score,
       at.id                    AS away_id,
       at.code                  AS away_code,
       m.away_score             AS away_score,
       m.penalty_winner_team_id AS penalty_winner_team_id,
       m.kickoff_utc            AS kickoff_utc
FROM matches m
JOIN teams ht ON ht.id = m.home_team_id
JOIN teams at ON at.id = m.away_team_id
LEFT JOIN celebration_views cv ON cv.match_id = m.id AND cv.user_id = ?
WHERE m.status = 'final' AND cv.match_id IS NULL
ORDER BY m.kickoff_utc DESC
`

type ListUnseenFinalMatchesForUserRow struct {
	MatchID             int64         `json:"match_id"`
	HomeID              int64         `json:"home_id"`
	HomeCode            string        `json:"home_code"`
	HomeScore           sql.NullInt32 `json:"home_score"`
	AwayID              int64         `json:"away_id"`
	AwayCode            string        `json:"away_code"`
	AwayScore           sql.NullInt32 `json:"away_score"`
	PenaltyWinnerTeamID sql.NullInt64 `json:"penalty_winner_team_id"`
	KickoffUtc          time.Time     `json:"kickoff_utc"`
}

// All FINAL matches the given user has not yet had a celebration recorded for,
// newest kickoff first. Win/allowlist filtering happens in Go (celebrationFor).
func (q *Queries) ListUnseenFinalMatchesForUser(ctx context.Context, userID int64) ([]ListUnseenFinalMatchesForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnseenFinalMatchesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnseenFinalMatchesForUserRow
	for rows.Next() {
		var i ListUnseenFinalMatchesForUserRow
		if err := rows.Scan(
			&i.MatchID,
			&i.HomeID,
			&i.HomeCode,
			&i.HomeScore,
			&i.AwayID,
			&i.AwayCode,
			&i.AwayScore,
			&i.PenaltyWinnerTeamID,
			&i.KickoffUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCelebrationSeen = `-- name: MarkCelebrationSeen :exec
INSERT INTO celebration_views (user_id, match_id)
VALUES (?, ?)
ON DUPLICATE KEY UPDATE seen_at = seen_at
`

type MarkCelebrationSeenParams struct {
	UserID  int64 `json:"user_id"`
	MatchID int64 `json:"match_id"`
}

func (q *Queries) MarkCelebrationSeen(ctx context.Context, arg MarkCelebrationSeenParams) error {
	_, err := q.db.ExecContext(ctx, markCelebrationSeen, arg.UserID, arg.MatchID)
	return err
}
