// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leaderboard.sql

package sqlc

import (
	"context"
	"time"
)

const listWeeklyResults = `-- name: ListWeeklyResults :many
SELECT user_id, points, is_winner
FROM weekly_results
WHERE week_start = ?
`

type ListWeeklyResultsRow struct {
	UserID   int64 `json:"user_id"`
	Points   int32 `json:"points"`
	IsWinner bool  `json:"is_winner"`
}

func (q *Queries) ListWeeklyResults(ctx context.Context, weekStart time.Time) ([]ListWeeklyResultsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWeeklyResults, weekStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWeeklyResultsRow
	for rows.Next() {
		var i ListWeeklyResultsRow
		if err := rows.Scan(&i.UserID, &i.Points, &i.IsWinner); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const overallLeaderboard = `-- name: OverallLeaderboard :many
SELECT u.id AS user_id, u.name, u.avatar_url,
       CAST(COALESCE(SUM(COALESCE(p.points,0) + COALESCE(p.penalty_bonus,0)), 0) AS SIGNED) AS points,
       CAST(COALESCE(SUM(CASE WHEN p.points = 5 THEN 1 ELSE 0 END), 0) AS SIGNED) AS exact_count,
       CAST(COALESCE(SUM(CASE WHEN p.points = 3 THEN 1 ELSE 0 END), 0) AS SIGNED) AS correct_count
FROM predictions p
JOIN users u ON u.id = p.user_id
GROUP BY u.id, u.name, u.avatar_url
ORDER BY points DESC, exact_count DESC, correct_count DESC, u.id ASC
`

type OverallLeaderboardRow struct {
	UserID       int64  `json:"user_id"`
	Name         string `json:"name"`
	AvatarUrl    string `json:"avatar_url"`
	Points       int64  `json:"points"`
	ExactCount   int64  `json:"exact_count"`
	CorrectCount int64  `json:"correct_count"`
}

// The INNER JOIN from predictions is deliberate: only users with >=1 prediction
// appear; zero-prediction users are intentionally excluded per the approved M6
// design. Do NOT change to a LEFT JOIN.
func (q *Queries) OverallLeaderboard(ctx context.Context) ([]OverallLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, overallLeaderboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OverallLeaderboardRow
	for rows.Next() {
		var i OverallLeaderboardRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.AvatarUrl,
			&i.Points,
			&i.ExactCount,
			&i.CorrectCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWeeklyResult = `-- name: UpsertWeeklyResult :exec
INSERT INTO weekly_results (user_id, week_start, points, is_winner)
VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE points = VALUES(points), is_winner = VALUES(is_winner)
`

type UpsertWeeklyResultParams struct {
	UserID    int64     `json:"user_id"`
	WeekStart time.Time `json:"week_start"`
	Points    int32     `json:"points"`
	IsWinner  bool      `json:"is_winner"`
}

func (q *Queries) UpsertWeeklyResult(ctx context.Context, arg UpsertWeeklyResultParams) error {
	_, err := q.db.ExecContext(ctx, upsertWeeklyResult,
		arg.UserID,
		arg.WeekStart,
		arg.Points,
		arg.IsWinner,
	)
	return err
}

const weeklyLeaderboard = `-- name: WeeklyLeaderboard :many
SELECT u.id AS user_id, u.name, u.avatar_url,
       CAST(COALESCE(SUM(COALESCE(p.points,0) + COALESCE(p.penalty_bonus,0)), 0) AS SIGNED) AS points,
       CAST(COALESCE(SUM(CASE WHEN p.points = 5 THEN 1 ELSE 0 END), 0) AS SIGNED) AS exact_count,
       CAST(COALESCE(SUM(CASE WHEN p.points = 3 THEN 1 ELSE 0 END), 0) AS SIGNED) AS correct_count
FROM predictions p
JOIN users u ON u.id = p.user_id
JOIN matches m ON m.id = p.match_id
WHERE m.kickoff_utc >= ? AND m.kickoff_utc < ?
GROUP BY u.id, u.name, u.avatar_url
ORDER BY points DESC, exact_count DESC, correct_count DESC, u.id ASC
`

type WeeklyLeaderboardParams struct {
	KickoffUtc   time.Time `json:"kickoff_utc"`
	KickoffUtc_2 time.Time `json:"kickoff_utc_2"`
}

type WeeklyLeaderboardRow struct {
	UserID       int64  `json:"user_id"`
	Name         string `json:"name"`
	AvatarUrl    string `json:"avatar_url"`
	Points       int64  `json:"points"`
	ExactCount   int64  `json:"exact_count"`
	CorrectCount int64  `json:"correct_count"`
}

// The INNER JOIN from predictions is deliberate: only users with >=1 prediction
// in the window appear; zero-prediction users are intentionally excluded per the
// approved M6 design. Do NOT change to a LEFT JOIN.
func (q *Queries) WeeklyLeaderboard(ctx context.Context, arg WeeklyLeaderboardParams) ([]WeeklyLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, weeklyLeaderboard, arg.KickoffUtc, arg.KickoffUtc_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WeeklyLeaderboardRow
	for rows.Next() {
		var i WeeklyLeaderboardRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.AvatarUrl,
			&i.Points,
			&i.ExactCount,
			&i.CorrectCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
