// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leaderboard.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const listWeeklyResults = `-- name: ListWeeklyResults :many
SELECT user_id, points, is_winner
FROM weekly_results
WHERE week_start = ?
`

type ListWeeklyResultsRow struct {
	UserID   int64 `json:"user_id"`
	Points   int32 `json:"points"`
	IsWinner bool  `json:"is_winner"`
}

func (q *Queries) ListWeeklyResults(ctx context.Context, weekStart time.Time) ([]ListWeeklyResultsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWeeklyResults, weekStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWeeklyResultsRow
	for rows.Next() {
		var i ListWeeklyResultsRow
		if err := rows.Scan(&i.UserID, &i.Points, &i.IsWinner); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWinners = `-- name: ListWinners :many
SELECT w.week_start, w.user_id, u.name, u.avatar_url, w.points, w.prize_paid, w.paid_at
FROM weekly_results w
JOIN users u ON u.id = w.user_id
WHERE w.is_winner = 1
ORDER BY w.week_start DESC, w.points DESC, u.id ASC
`

type ListWinnersRow struct {
	WeekStart time.Time    `json:"week_start"`
	UserID    int64        `json:"user_id"`
	Name      string       `json:"name"`
	AvatarUrl string       `json:"avatar_url"`
	Points    int32        `json:"points"`
	PrizePaid bool         `json:"prize_paid"`
	PaidAt    sql.NullTime `json:"paid_at"`
}

func (q *Queries) ListWinners(ctx context.Context) ([]ListWinnersRow, error) {
	rows, err := q.db.QueryContext(ctx, listWinners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWinnersRow
	for rows.Next() {
		var i ListWinnersRow
		if err := rows.Scan(
			&i.WeekStart,
			&i.UserID,
			&i.Name,
			&i.AvatarUrl,
			&i.Points,
			&i.PrizePaid,
			&i.PaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWinnerPaid = `-- name: MarkWinnerPaid :execrows
UPDATE weekly_results
SET prize_paid = ?, paid_at = ?
WHERE week_start = ? AND user_id = ? AND is_winner = 1
`

type MarkWinnerPaidParams struct {
	PrizePaid bool         `json:"prize_paid"`
	PaidAt    sql.NullTime `json:"paid_at"`
	WeekStart time.Time    `json:"week_start"`
	UserID    int64        `json:"user_id"`
}

func (q *Queries) MarkWinnerPaid(ctx context.Context, arg MarkWinnerPaidParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markWinnerPaid,
		arg.PrizePaid,
		arg.PaidAt,
		arg.WeekStart,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const overallLeaderboard = `-- name: OverallLeaderboard :many
SELECT u.id AS user_id, u.name, u.avatar_url,
       CAST(SUM(COALESCE(p.points,0) + COALESCE(p.penalty_bonus,0)) + COALESCE(b.bonus_points,0) AS SIGNED) AS points,
       CAST(SUM(CASE WHEN p.points = 5 THEN 1 ELSE 0 END) AS SIGNED) AS exact_count,
       CAST(SUM(CASE WHEN p.points = 3 THEN 1 ELSE 0 END) AS SIGNED) AS correct_count,
       CAST(COALESCE(b.bonus_hits,0) AS SIGNED) AS bonus_hits
FROM predictions p
JOIN users u ON u.id = p.user_id
LEFT JOIN (
  SELECT user_id,
         SUM(COALESCE(points,0)) AS bonus_points,
         SUM(CASE WHEN points > 0 THEN 1 ELSE 0 END) AS bonus_hits
  FROM bonus_predictions GROUP BY user_id
) b ON b.user_id = u.id
GROUP BY u.id, u.name, u.avatar_url, b.bonus_points, b.bonus_hits
ORDER BY points DESC, exact_count DESC, correct_count DESC, bonus_hits DESC, u.id ASC
`

type OverallLeaderboardRow struct {
	UserID       int64  `json:"user_id"`
	Name         string `json:"name"`
	AvatarUrl    string `json:"avatar_url"`
	Points       int64  `json:"points"`
	ExactCount   int64  `json:"exact_count"`
	CorrectCount int64  `json:"correct_count"`
	BonusHits    int64  `json:"bonus_hits"`
}

// The INNER JOIN from predictions is deliberate: only users with >=1 prediction
// appear; zero-prediction users are intentionally excluded per the approved M6
// design. Do NOT change the predictions JOIN to a LEFT JOIN.
// Bonus points (tournament-wide, not per-week) are added via a LEFT JOIN subquery
// so users with no bonus picks still appear with bonus_points=0, bonus_hits=0.
func (q *Queries) OverallLeaderboard(ctx context.Context) ([]OverallLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, overallLeaderboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OverallLeaderboardRow
	for rows.Next() {
		var i OverallLeaderboardRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.AvatarUrl,
			&i.Points,
			&i.ExactCount,
			&i.CorrectCount,
			&i.BonusHits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWeeklyResult = `-- name: UpsertWeeklyResult :exec
INSERT INTO weekly_results (user_id, week_start, points, is_winner)
VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE points = VALUES(points), is_winner = VALUES(is_winner)
`

type UpsertWeeklyResultParams struct {
	UserID    int64     `json:"user_id"`
	WeekStart time.Time `json:"week_start"`
	Points    int32     `json:"points"`
	IsWinner  bool      `json:"is_winner"`
}

func (q *Queries) UpsertWeeklyResult(ctx context.Context, arg UpsertWeeklyResultParams) error {
	_, err := q.db.ExecContext(ctx, upsertWeeklyResult,
		arg.UserID,
		arg.WeekStart,
		arg.Points,
		arg.IsWinner,
	)
	return err
}

const weeklyLeaderboard = `-- name: WeeklyLeaderboard :many
SELECT u.id AS user_id, u.name, u.avatar_url,
       CAST(COALESCE(SUM(COALESCE(p.points,0) + COALESCE(p.penalty_bonus,0)), 0) AS SIGNED) AS points,
       CAST(COALESCE(SUM(CASE WHEN p.points = 5 THEN 1 ELSE 0 END), 0) AS SIGNED) AS exact_count,
       CAST(COALESCE(SUM(CASE WHEN p.points = 3 THEN 1 ELSE 0 END), 0) AS SIGNED) AS correct_count
FROM predictions p
JOIN users u ON u.id = p.user_id
JOIN matches m ON m.id = p.match_id
WHERE m.kickoff_utc >= ? AND m.kickoff_utc < ?
GROUP BY u.id, u.name, u.avatar_url
ORDER BY points DESC, exact_count DESC, correct_count DESC, u.id ASC
`

type WeeklyLeaderboardParams struct {
	KickoffUtc   time.Time `json:"kickoff_utc"`
	KickoffUtc_2 time.Time `json:"kickoff_utc_2"`
}

type WeeklyLeaderboardRow struct {
	UserID       int64  `json:"user_id"`
	Name         string `json:"name"`
	AvatarUrl    string `json:"avatar_url"`
	Points       int64  `json:"points"`
	ExactCount   int64  `json:"exact_count"`
	CorrectCount int64  `json:"correct_count"`
}

// The INNER JOIN from predictions is deliberate: only users with >=1 prediction
// in the window appear; zero-prediction users are intentionally excluded per the
// approved M6 design. Do NOT change to a LEFT JOIN.
func (q *Queries) WeeklyLeaderboard(ctx context.Context, arg WeeklyLeaderboardParams) ([]WeeklyLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, weeklyLeaderboard, arg.KickoffUtc, arg.KickoffUtc_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WeeklyLeaderboardRow
	for rows.Next() {
		var i WeeklyLeaderboardRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.AvatarUrl,
			&i.Points,
			&i.ExactCount,
			&i.CorrectCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
