// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const listMatchesWithTeams = `-- name: ListMatchesWithTeams :many
SELECT
    m.id, m.api_fixture_id, m.stage, m.round,
    m.kickoff_utc, m.status, m.home_score, m.away_score,
    m.went_to_penalties, m.penalty_winner_team_id, m.manual_override,
    ht.id AS home_id, ht.name AS home_name, ht.code AS home_code, ht.logo_url AS home_logo,
    at.id AS away_id, at.name AS away_name, at.code AS away_code, at.logo_url AS away_logo
FROM matches m
JOIN teams ht ON ht.id = m.home_team_id
JOIN teams at ON at.id = m.away_team_id
ORDER BY m.kickoff_utc
`

type ListMatchesWithTeamsRow struct {
	ID                  int64         `json:"id"`
	ApiFixtureID        int64         `json:"api_fixture_id"`
	Stage               MatchesStage  `json:"stage"`
	Round               string        `json:"round"`
	KickoffUtc          time.Time     `json:"kickoff_utc"`
	Status              MatchesStatus `json:"status"`
	HomeScore           sql.NullInt32 `json:"home_score"`
	AwayScore           sql.NullInt32 `json:"away_score"`
	WentToPenalties     bool          `json:"went_to_penalties"`
	PenaltyWinnerTeamID sql.NullInt64 `json:"penalty_winner_team_id"`
	ManualOverride      bool          `json:"manual_override"`
	HomeID              int64         `json:"home_id"`
	HomeName            string        `json:"home_name"`
	HomeCode            string        `json:"home_code"`
	HomeLogo            string        `json:"home_logo"`
	AwayID              int64         `json:"away_id"`
	AwayName            string        `json:"away_name"`
	AwayCode            string        `json:"away_code"`
	AwayLogo            string        `json:"away_logo"`
}

func (q *Queries) ListMatchesWithTeams(ctx context.Context) ([]ListMatchesWithTeamsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMatchesWithTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchesWithTeamsRow
	for rows.Next() {
		var i ListMatchesWithTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.ApiFixtureID,
			&i.Stage,
			&i.Round,
			&i.KickoffUtc,
			&i.Status,
			&i.HomeScore,
			&i.AwayScore,
			&i.WentToPenalties,
			&i.PenaltyWinnerTeamID,
			&i.ManualOverride,
			&i.HomeID,
			&i.HomeName,
			&i.HomeCode,
			&i.HomeLogo,
			&i.AwayID,
			&i.AwayName,
			&i.AwayCode,
			&i.AwayLogo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMatch = `-- name: UpsertMatch :execresult
INSERT INTO matches (
    api_fixture_id, stage, round, home_team_id, away_team_id,
    kickoff_utc, status, home_score, away_score, went_to_penalties, penalty_winner_team_id
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    stage                  = IF(manual_override = 1, stage, VALUES(stage)),
    round                  = IF(manual_override = 1, round, VALUES(round)),
    home_team_id           = IF(manual_override = 1, home_team_id, VALUES(home_team_id)),
    away_team_id           = IF(manual_override = 1, away_team_id, VALUES(away_team_id)),
    kickoff_utc            = IF(manual_override = 1, kickoff_utc, VALUES(kickoff_utc)),
    status                 = IF(manual_override = 1, status, VALUES(status)),
    home_score             = IF(manual_override = 1, home_score, VALUES(home_score)),
    away_score             = IF(manual_override = 1, away_score, VALUES(away_score)),
    went_to_penalties      = IF(manual_override = 1, went_to_penalties, VALUES(went_to_penalties)),
    penalty_winner_team_id = IF(manual_override = 1, penalty_winner_team_id, VALUES(penalty_winner_team_id))
`

type UpsertMatchParams struct {
	ApiFixtureID        int64         `json:"api_fixture_id"`
	Stage               MatchesStage  `json:"stage"`
	Round               string        `json:"round"`
	HomeTeamID          int64         `json:"home_team_id"`
	AwayTeamID          int64         `json:"away_team_id"`
	KickoffUtc          time.Time     `json:"kickoff_utc"`
	Status              MatchesStatus `json:"status"`
	HomeScore           sql.NullInt32 `json:"home_score"`
	AwayScore           sql.NullInt32 `json:"away_score"`
	WentToPenalties     bool          `json:"went_to_penalties"`
	PenaltyWinnerTeamID sql.NullInt64 `json:"penalty_winner_team_id"`
}

func (q *Queries) UpsertMatch(ctx context.Context, arg UpsertMatchParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, upsertMatch,
		arg.ApiFixtureID,
		arg.Stage,
		arg.Round,
		arg.HomeTeamID,
		arg.AwayTeamID,
		arg.KickoffUtc,
		arg.Status,
		arg.HomeScore,
		arg.AwayScore,
		arg.WentToPenalties,
		arg.PenaltyWinnerTeamID,
	)
}
