// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type MatchesStage string

const (
	MatchesStageGroup    MatchesStage = "group"
	MatchesStageKnockout MatchesStage = "knockout"
)

func (e *MatchesStage) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MatchesStage(s)
	case string:
		*e = MatchesStage(s)
	default:
		return fmt.Errorf("unsupported scan type for MatchesStage: %T", src)
	}
	return nil
}

type NullMatchesStage struct {
	MatchesStage MatchesStage `json:"matches_stage"`
	Valid        bool         `json:"valid"` // Valid is true if MatchesStage is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMatchesStage) Scan(value interface{}) error {
	if value == nil {
		ns.MatchesStage, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MatchesStage.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMatchesStage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MatchesStage), nil
}

type MatchesStatus string

const (
	MatchesStatusScheduled MatchesStatus = "scheduled"
	MatchesStatusLive      MatchesStatus = "live"
	MatchesStatusFinal     MatchesStatus = "final"
)

func (e *MatchesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MatchesStatus(s)
	case string:
		*e = MatchesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MatchesStatus: %T", src)
	}
	return nil
}

type NullMatchesStatus struct {
	MatchesStatus MatchesStatus `json:"matches_status"`
	Valid         bool          `json:"valid"` // Valid is true if MatchesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMatchesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MatchesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MatchesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMatchesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MatchesStatus), nil
}

type UsersRole string

const (
	UsersRoleUser  UsersRole = "user"
	UsersRoleAdmin UsersRole = "admin"
)

func (e *UsersRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersRole(s)
	case string:
		*e = UsersRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersRole: %T", src)
	}
	return nil
}

type NullUsersRole struct {
	UsersRole UsersRole `json:"users_role"`
	Valid     bool      `json:"valid"` // Valid is true if UsersRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersRole) Scan(value interface{}) error {
	if value == nil {
		ns.UsersRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersRole), nil
}

type Match struct {
	ID                  int64         `json:"id"`
	SourceID            int64         `json:"source_id"`
	MatchNumber         int32         `json:"match_number"`
	Stage               MatchesStage  `json:"stage"`
	Round               string        `json:"round"`
	GroupLetter         string        `json:"group_letter"`
	MatchLabel          string        `json:"match_label"`
	HomeTeamID          sql.NullInt64 `json:"home_team_id"`
	AwayTeamID          sql.NullInt64 `json:"away_team_id"`
	VenueID             sql.NullInt64 `json:"venue_id"`
	KickoffUtc          time.Time     `json:"kickoff_utc"`
	Status              MatchesStatus `json:"status"`
	HomeScore           sql.NullInt32 `json:"home_score"`
	AwayScore           sql.NullInt32 `json:"away_score"`
	WentToPenalties     bool          `json:"went_to_penalties"`
	PenaltyWinnerTeamID sql.NullInt64 `json:"penalty_winner_team_id"`
	ManualOverride      bool          `json:"manual_override"`
	UpdatedAt           time.Time     `json:"updated_at"`
	ApiFixtureID        sql.NullInt64 `json:"api_fixture_id"`
}

type Prediction struct {
	ID                  int64         `json:"id"`
	UserID              int64         `json:"user_id"`
	MatchID             int64         `json:"match_id"`
	HomeScore           int32         `json:"home_score"`
	AwayScore           int32         `json:"away_score"`
	PenaltyWinnerTeamID sql.NullInt64 `json:"penalty_winner_team_id"`
	Points              sql.NullInt32 `json:"points"`
	PenaltyBonus        sql.NullInt32 `json:"penalty_bonus"`
	CreatedAt           time.Time     `json:"created_at"`
	UpdatedAt           time.Time     `json:"updated_at"`
}

type Team struct {
	ID            int64  `json:"id"`
	SourceID      int64  `json:"source_id"`
	Name          string `json:"name"`
	Code          string `json:"code"`
	GroupLetter   string `json:"group_letter"`
	IsPlaceholder bool   `json:"is_placeholder"`
}

type User struct {
	ID        int64     `json:"id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	AvatarUrl string    `json:"avatar_url"`
	Role      UsersRole `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

type Venue struct {
	ID            int64  `json:"id"`
	SourceID      int64  `json:"source_id"`
	CityName      string `json:"city_name"`
	Country       string `json:"country"`
	VenueName     string `json:"venue_name"`
	RegionCluster string `json:"region_cluster"`
	AirportCode   string `json:"airport_code"`
}

type WeeklyResult struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	WeekStart time.Time    `json:"week_start"`
	Points    int32        `json:"points"`
	IsWinner  bool         `json:"is_winner"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	PrizePaid bool         `json:"prize_paid"`
	PaidAt    sql.NullTime `json:"paid_at"`
}
