// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package sqlc

import (
	"context"
)

const listTeamsForPicker = `-- name: ListTeamsForPicker :many
SELECT id, name, code FROM teams WHERE is_placeholder = 0 ORDER BY name ASC
`

type ListTeamsForPickerRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Code string `json:"code"`
}

func (q *Queries) ListTeamsForPicker(ctx context.Context) ([]ListTeamsForPickerRow, error) {
	rows, err := q.db.QueryContext(ctx, listTeamsForPicker)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamsForPickerRow
	for rows.Next() {
		var i ListTeamsForPickerRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Code); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const playerExists = `-- name: PlayerExists :one
SELECT COUNT(*) FROM players WHERE id = ?
`

func (q *Queries) PlayerExists(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, playerExists, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const searchPlayers = `-- name: SearchPlayers :many
SELECT p.id, p.name, p.position, t.code AS team_code
FROM players p JOIN teams t ON t.id = p.team_id
WHERE p.name LIKE CONCAT('%', ?, '%')
ORDER BY p.name ASC
LIMIT 20
`

type SearchPlayersRow struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Position string `json:"position"`
	TeamCode string `json:"team_code"`
}

func (q *Queries) SearchPlayers(ctx context.Context, concat interface{}) ([]SearchPlayersRow, error) {
	rows, err := q.db.QueryContext(ctx, searchPlayers, concat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPlayersRow
	for rows.Next() {
		var i SearchPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Position,
			&i.TeamCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const teamExists = `-- name: TeamExists :one
SELECT COUNT(*) FROM teams WHERE id = ? AND is_placeholder = 0
`

func (q *Queries) TeamExists(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, teamExists, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const upsertPlayer = `-- name: UpsertPlayer :exec
INSERT INTO players (source_id, team_id, name, position)
VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE team_id = VALUES(team_id), name = VALUES(name), position = VALUES(position)
`

type UpsertPlayerParams struct {
	SourceID int64  `json:"source_id"`
	TeamID   int64  `json:"team_id"`
	Name     string `json:"name"`
	Position string `json:"position"`
}

func (q *Queries) UpsertPlayer(ctx context.Context, arg UpsertPlayerParams) error {
	_, err := q.db.ExecContext(ctx, upsertPlayer,
		arg.SourceID,
		arg.TeamID,
		arg.Name,
		arg.Position,
	)
	return err
}
