// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlc

import (
	"context"
)

const getSetting = `-- name: GetSetting :one
SELECT value FROM settings WHERE ` + "`" + `key` + "`" + ` = ?
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const listSettings = `-- name: ListSettings :many
SELECT ` + "`" + `key` + "`" + `, value FROM settings
`

type ListSettingsRow struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) ListSettings(ctx context.Context) ([]ListSettingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSettingsRow
	for rows.Next() {
		var i ListSettingsRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO settings (` + "`" + `key` + "`" + `, ` + "`" + `value` + "`" + `) VALUES (?, ?)
ON DUPLICATE KEY UPDATE value = VALUES(value)
`

type UpsertSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting, arg.Key, arg.Value)
	return err
}
