// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getTeamByAPIID = `-- name: GetTeamByAPIID :one
SELECT id, api_team_id, name, code, logo_url
FROM teams WHERE api_team_id = ?
`

func (q *Queries) GetTeamByAPIID(ctx context.Context, apiTeamID int64) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeamByAPIID, apiTeamID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.ApiTeamID,
		&i.Name,
		&i.Code,
		&i.LogoUrl,
	)
	return i, err
}

const listTeams = `-- name: ListTeams :many
SELECT id, api_team_id, name, code, logo_url
FROM teams ORDER BY name
`

func (q *Queries) ListTeams(ctx context.Context) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, listTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.ApiTeamID,
			&i.Name,
			&i.Code,
			&i.LogoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTeam = `-- name: UpsertTeam :execresult
INSERT INTO teams (api_team_id, name, code, logo_url)
VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    code = VALUES(code),
    logo_url = VALUES(logo_url)
`

type UpsertTeamParams struct {
	ApiTeamID int64  `json:"api_team_id"`
	Name      string `json:"name"`
	Code      string `json:"code"`
	LogoUrl   string `json:"logo_url"`
}

func (q *Queries) UpsertTeam(ctx context.Context, arg UpsertTeamParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, upsertTeam,
		arg.ApiTeamID,
		arg.Name,
		arg.Code,
		arg.LogoUrl,
	)
}
