// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package sqlc

import (
	"context"
)

const getTeamIDBySourceID = `-- name: GetTeamIDBySourceID :one
SELECT id FROM teams WHERE source_id = ?
`

func (q *Queries) GetTeamIDBySourceID(ctx context.Context, sourceID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTeamIDBySourceID, sourceID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listTeamsByCode = `-- name: ListTeamsByCode :many
SELECT id, code FROM teams WHERE is_placeholder = 0
`

type ListTeamsByCodeRow struct {
	ID   int64  `json:"id"`
	Code string `json:"code"`
}

func (q *Queries) ListTeamsByCode(ctx context.Context) ([]ListTeamsByCodeRow, error) {
	rows, err := q.db.QueryContext(ctx, listTeamsByCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamsByCodeRow
	for rows.Next() {
		var i ListTeamsByCodeRow
		if err := rows.Scan(&i.ID, &i.Code); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTeam = `-- name: UpsertTeam :exec
INSERT INTO teams (source_id, name, code, group_letter, is_placeholder)
VALUES (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    name = VALUES(name), code = VALUES(code),
    group_letter = VALUES(group_letter), is_placeholder = VALUES(is_placeholder)
`

type UpsertTeamParams struct {
	SourceID      int64  `json:"source_id"`
	Name          string `json:"name"`
	Code          string `json:"code"`
	GroupLetter   string `json:"group_letter"`
	IsPlaceholder bool   `json:"is_placeholder"`
}

func (q *Queries) UpsertTeam(ctx context.Context, arg UpsertTeamParams) error {
	_, err := q.db.ExecContext(ctx, upsertTeam,
		arg.SourceID,
		arg.Name,
		arg.Code,
		arg.GroupLetter,
		arg.IsPlaceholder,
	)
	return err
}
