// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: venues.sql

package sqlc

import (
	"context"
)

const getVenueIDBySourceID = `-- name: GetVenueIDBySourceID :one
SELECT id FROM venues WHERE source_id = ?
`

func (q *Queries) GetVenueIDBySourceID(ctx context.Context, sourceID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getVenueIDBySourceID, sourceID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertVenue = `-- name: UpsertVenue :exec
INSERT INTO venues (source_id, city_name, country, venue_name, region_cluster, airport_code)
VALUES (?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    city_name = VALUES(city_name), country = VALUES(country),
    venue_name = VALUES(venue_name), region_cluster = VALUES(region_cluster),
    airport_code = VALUES(airport_code)
`

type UpsertVenueParams struct {
	SourceID      int64  `json:"source_id"`
	CityName      string `json:"city_name"`
	Country       string `json:"country"`
	VenueName     string `json:"venue_name"`
	RegionCluster string `json:"region_cluster"`
	AirportCode   string `json:"airport_code"`
}

func (q *Queries) UpsertVenue(ctx context.Context, arg UpsertVenueParams) error {
	_, err := q.db.ExecContext(ctx, upsertVenue,
		arg.SourceID,
		arg.CityName,
		arg.Country,
		arg.VenueName,
		arg.RegionCluster,
		arg.AirportCode,
	)
	return err
}
